[package]
name = "naryx_inventory_reservation"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "naryx_inventory_reservation"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build", "naryx_core/idl-build"]
anchor-debug = []
custom-heap = []
custom-panic = []


[dependencies]
anchor-lang = { version = "=1.2.0", features = ["init-if-needed"] }
anchor-spl = { version = "=1.2.0", features = ["associated_token", "token"] }
naryx_core = { path = "../naryx_core", features = ["cpi"] }
solana-sha256-hasher = { version = "=3.1.0", features = ["sha2"] }


[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }
