export {
  NaryxApiError,
  NaryxClient,
  NaryxEvidenceError,
  base58Encode,
  base58Decode,
  candlesFromTape,
  verifyAllocationEvidence,
  verifyOutcomeEvidence,
  verifyTerminalEvidence,
  type CandlePage,
  type ObservedTrade,
  type PackageOpportunity,
  type QualificationView,
  type VerifiedQualificationRecord,
  type SeriesCurve,
  type SeriesCurvePoint,
  type SizeQuoteView,
  type VerifiedOrderQuote,
  type VerifiedPositionSource,
  type VerifiedPositions,
  type VerifiedMarketCatalogue,
  type VerifiedStrategyCommand,
  type StrategyCommandSigner,
  type VerifiedRouteDecision,
  type VerifiedSolverManifest,
  type VerifiedOutcome,
  type ExecutionQualityView,
  type SolverPerformanceView,
  type FetchLike,
  type NaryxClientOptions,
  type OrderSigner,
  type OrderStatusView,
  type PackageBookLevelView,
  type PackageDepth,
  type PackageMarketSummary,
  type PackageTapePage,
  type PackageTapeTrade,
  type RegisteredDocumentView,
  type SubmittedOrder,
  type VerifiedAllocation,
  type VerifiedTerminalEvidence,
} from './client.js';
export { NaryxSolverClient, type NaryxSolverClientOptions, type OpenOrderPage } from './solver-client.js';

// Evidence verifiers an integrator can run without any Naryx service in the loop.
export {
  aggregateCandles,
  evidenceManifestHash,
  executablePackageIndex,
  packageAllocationHash,
  packageOrderBytes,
  packageOrderHash,
  packageReceiptHash,
  privacyProfile,
  replayRouteDecision,
  replaySealedAuction,
  strategyStateHash,
  terminalOutcomeHash,
  verifyOutcomeReceiptLink,
  verifyPackageAllocation,
  verifyReceiptFees,
  verifySealedAuctionResult,
  verifySelectiveDisclosure,
} from '@naryx/protocol-types';
