export {
  NaryxApiError,
  NaryxClient,
  NaryxEvidenceError,
  base58Encode,
  base58Decode,
  candlesFromTape,
  verifyAllocationEvidence,
  verifyOutcomeEvidence,
  verifyTerminalEvidence,
  type CandlePage,
  type ObservedTrade,
  type PackageOpportunity,
  type QualificationView,
  type VerifiedQualificationRecord,
  type SeriesCurve,
  type SeriesCurvePoint,
  type SizeQuoteView,
  type VerifiedOrderQuote,
  type VerifiedPositionSource,
  type VerifiedPositions,
  type VerifiedMarketCatalogue,
  type VerifiedStrategyCommand,
  type StrategyCommandSigner,
  type VerifiedRouteDecision,
  type VerifiedSolverManifest,
  type VerifiedOutcome,
  type ExecutionQualityView,
  type SolverPerformanceView,
  type FetchLike,
  type NaryxClientOptions,
  type OrderSigner,
  type OrderStatusView,
  type PackageBookLevelView,
  type PackageDepth,
  type PackageMarketSummary,
  type PackageTapePage,
  type PackageTapeTrade,
  type RegisteredDocumentView,
  type SubmittedOrder,
  type VerifiedAllocation,
  type PackageReopeningOrderSubmission,
  type VerifiedPackageReopening,
  type PackageBookAmendmentResult,
  type VerifiedTerminalEvidence,
} from './client.js';
export {
  NaryxSolverClient,
  type EligibleAuctionPage,
  type NaryxSolverClientOptions,
  type OpenOrderPage,
} from './solver-client.js';

// Evidence verifiers an integrator can run without any Naryx service in the loop.
export {
  aggregateCandles,
  evidenceManifestHash,
  executablePackageIndex,
  fromProtocolJson,
  packageAllocationHash,
  packageOrderBytes,
  packageOrderHash,
  packageReceiptHash,
  privacyProfile,
  replayRouteDecision,
  replaySealedAuction,
  strategyStateHash,
  terminalOutcomeHash,
  verifyOutcomeReceiptLink,
  verifyPackageAllocation,
  verifyReceiptFees,
  verifySealedAuctionResult,
  verifySelectiveDisclosure,
} from '@naryx/protocol-types';
export { createQuoteAutomation, type QuoteAutomation, type QuoteAutomationAction, type QuoteAutomationPolicy } from './maker-automation.js';
export {
  createImpliedLiquidityAutomation,
  type ImpliedLegBookSnapshot,
  type ImpliedLegLevel,
  type ImpliedLiquidityAutomation,
  type ImpliedLiquidityAutomationAction,
  type ImpliedLiquidityAutomationPolicy,
} from './implied-liquidity-automation.js';
export {
  NARYX_RFQ_HPKE_SUITE_ID,
  NARYX_RFQ_HPKE_PUBLIC_KEY_BYTES,
  NARYX_RFQ_HPKE_PRIVATE_KEY_BYTES,
  NARYX_RFQ_HPKE_ENCAPSULATED_KEY_BYTES,
  NARYX_RFQ_MAX_PLAINTEXT_BYTES,
  NaryxPrivateRfqCryptoError,
  generateNaryxRfqHpkeKeyPair,
  encryptPrivateRfqRequest,
  decryptPrivateRfqRequest,
  encryptPrivateRfqResponse,
  decryptPrivateRfqResponse,
  type PrivateRfqEnvelopeHeaderInput,
  type NaryxRfqHpkeKeyPair,
} from './private-rfq-crypto.js';
