[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
naryx_conformance_venue = "ERGvPwyenaZDcAr9cyni7paeXPQ72NKC75ozz1fjCY7y"
naryx_core = "8qmA9VuQwAAqQ3F93CAfLNFB3P8M8ygXgvn9xCnZXa2i"
naryx_orca_adapter = "J3kJZ6SP1dGW2TLNYfGJrujmecsfkGkeUzcGbR6EJs5w"
naryx_rise_adapter = "7USHejoffnm7UgDhSJeF6mjT2gpEAwqRjyVmYXWx1TzP"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
