[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
naryx_conformance_venue = "ERGvPwyenaZDcAr9cyni7paeXPQ72NKC75ozz1fjCY7y"
naryx_core = "GpwzEWfFySnTdRp8iTPYz9AmsbePDeeC5ThGhMV5PxPq"
naryx_inventory_reservation = "8Dby697KuRBW1TsGucdXdQugVoko4WoJXRUTZdHfy4Dx"
naryx_orca_adapter = "Ao5mbjTPVAoM4SVobYMyaQwPRKruk9Rd7CF1ENL1xjUU"
naryx_package_book = "EvE2mjwHrtfQgNu8Whh6QGZBmkzxRjKadsHi4Uqk96dc"
naryx_rise_adapter = "9FAYFVXcJYqxcpw7bf6eK6iY6SkwYx6T4PT7NF3VjfzQ"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
