import { sha256 } from '@noble/hashes/sha2.js';
import { assertUint8Array, concatBytes } from './bytes.js';
import { MalformedInputError } from './errors.js';
import { hash32, type Hash32 } from './primitives.js';
import { encodeAscii } from './text.js';

export const HASH_DOMAIN = Object.freeze({
  ORDER: 'CON/v1/order',
  ROUTE: 'CON/v1/route',
  ROUTE_ACCOUNTS: 'CON/v1/route-accounts',
  QUOTE: 'CON/v1/quote',
  RESERVATION_ID: 'CON/v1/reservation-id',
  SOLVER_SIGNATURE: 'CON/v1/solver-signature',
  OUTCOME: 'CON/v1/outcome',
  RECEIPT: 'CON/v1/receipt',
  EVIDENCE_MANIFEST: 'CON/v1/evidence-manifest',
  BENCHMARK_MANIFEST: 'CON/v1/benchmark-manifest',
  BENCHMARK_ARM: 'CON/v1/benchmark-arm',
  BENCHMARK_PAIR: 'CON/v1/benchmark-pair',
  PACKAGE_TEMPLATE: 'CON/v1/package-template',
  ECONOMIC_STRATEGY_SERIES: 'CON/v1/economic-strategy-series',
  SERIES_EXECUTION_CLASS: 'CON/v1/series-execution-class',
  PACKAGE_TEMPLATE_REGISTRY_RECORD: 'CON/v1/package-template-registry-record',
  DOMAIN_MANIFEST: 'CON/v1/domain-manifest',
  ASSET_MANIFEST: 'CON/v1/asset-manifest',
  VENUE_MANIFEST: 'CON/v1/venue-manifest',
  MARKET_MANIFEST: 'CON/v1/market-manifest',
  ADAPTER_MANIFEST: 'CON/v1/adapter-manifest',
  PRICE_SOURCE_MANIFEST: 'CON/v1/price-source-manifest',
  DOMAIN_REGISTRY_RECORD: 'CON/v1/domain-registry-record',
  FEE_POLICY: 'CON/v1/fee-policy',
  SOLVER_CAPABILITY: 'CON/v1/solver-capability',
  PRIVATE_RFQ_ENVELOPE: 'CON/v1/private-rfq-envelope',
  PROTOCOL_ID_IDENTITY: 'CON/v1/protocol-id-identity',
  DOMAIN_REF_IDENTITY: 'CON/v1/domain-ref-identity',
  SETTLEMENT_CLASS_IDENTITY: 'CON/v1/settlement-class-identity',
  CASH_CARRY_SERIES_IDENTITY: 'CON/v1/cash-carry-series-identity',
  CASH_CARRY_SERIES_BINDING: 'CON/v1/cash-carry-series-binding',
  ASYNC_BONDED_AUTHORIZATION: 'CON/v1/async-bonded-authorization',
  ASYNC_BONDED_TRANSITION: 'CON/v1/async-bonded-transition',
  PACKAGE_LIFECYCLE_INTENT: 'CON/v1/package-lifecycle-intent',
  PACKAGE_LIFECYCLE_RECEIPT: 'CON/v1/package-lifecycle-receipt',
  AUTHORITY_INVENTORY: 'CON/v1/authority-inventory',
  OPERATION_CAP_POLICY: 'CON/v1/operation-cap-policy',
  FUNDED_OPERATION_MANIFEST: 'CON/v1/funded-operation-manifest',
  SECURITY_FINDING_SUMMARY: 'CON/v1/security-finding-summary',
  READINESS_EVIDENCE: 'CON/v1/readiness-evidence',
  READINESS_DECISION: 'CON/v1/readiness-decision',
  OPERATION_LEDGER_RECORD: 'CON/v1/operation-ledger-record',
  PACKAGE_MATCHING_POLICY: 'CON/v1/package-matching-policy',
  PACKAGE_TAKER_ORDER: 'CON/v1/package-taker-order',
  PACKAGE_BOOK_CANCELLATION: 'CON/v1/package-book-cancellation',
  PACKAGE_BOOK_AMENDMENT: 'CON/v1/package-book-amendment',
  PACKAGE_BOOK_HALT: 'CON/v1/package-book-halt',
  PACKAGE_SETTLEMENT_COMMITMENT: 'CON/v1/package-settlement-commitment',
  PACKAGE_SETTLEMENT_HANDOFF: 'CON/v1/package-settlement-handoff',
  PACKAGE_SETTLEMENT_READINESS: 'CON/v1/package-settlement-readiness',
  PACKAGE_QUOTE_EXECUTION_BINDING: 'CON/v1/package-quote-execution-binding',
  IMPLIED_PACKAGE_QUOTE: 'CON/v1/implied-package-quote',
  PACKAGE_IMPLICATION_PROOF: 'CON/v1/package-implication-proof',
  PACKAGE_ALLOCATION: 'CON/v1/package-allocation',
  PACKAGE_REOPENING_SNAPSHOT: 'CON/v1/package-reopening-snapshot',
  PACKAGE_REOPENING_RESULT: 'CON/v1/package-reopening-result',
  PACKAGE_REOPENING_SETTLEMENT_HANDOFF: 'CON/v1/package-reopening-settlement-handoff',
  SOLVER_CAPACITY_RECORD: 'CON/v1/solver-capacity-record',
  SOLVER_COMMITMENT_ROOT: 'CON/v1/solver-commitment-root',
  RFQ_DECISION: 'CON/v1/rfq-decision',
  PERFORMANCE_BOND: 'CON/v1/performance-bond',
  NETTING_POLICY: 'CON/v1/netting-policy',
  NETTING_INSTRUMENT: 'CON/v1/netting-instrument',
  NETTING_OBLIGATION: 'CON/v1/netting-obligation',
  NETTING_PROOF: 'CON/v1/netting-proof',
  NETTING_EXTERNAL_EXECUTION_INTENT: 'CON/v1/netting-external-execution-intent',
  NETTING_EXTERNAL_EXECUTION_EVIDENCE: 'CON/v1/netting-external-execution-evidence',
  NETTING_ALLOCATION_RECEIPT: 'CON/v1/netting-allocation-receipt',
  NETTING_FINAL_ALLOCATION_RECEIPT: 'CON/v1/netting-final-allocation-receipt',
  NETTING_ALLOCATION_EXECUTION_AUTHORIZATION: 'CON/v1/netting-allocation-execution-authorization',
  NETTING_ALLOCATION_SETTLEMENT_EVIDENCE: 'CON/v1/netting-allocation-settlement-evidence',
  NETTING_SETTLEMENT_COMPLETION_RECEIPT: 'CON/v1/netting-settlement-completion-receipt',
  CROSS_BATCH_CLEARING_POLICY: 'CON/v1/cross-batch-clearing-policy',
  CROSS_BATCH_CLEARING_PLAN: 'CON/v1/cross-batch-clearing-plan',
  CROSS_BATCH_EXECUTION_INTENT: 'CON/v1/cross-batch-execution-intent',
  CROSS_BATCH_EXECUTION_EVIDENCE: 'CON/v1/cross-batch-execution-evidence',
  CROSS_BATCH_CLEARING_RECEIPT: 'CON/v1/cross-batch-clearing-receipt',
  NATIVE_CLEARING_POLICY: 'CON/v1/native-clearing-policy',
  NATIVE_CLEARING_DOMAIN_STATE: 'CON/v1/native-clearing-domain-state',
  NATIVE_CLEARING_ACCOUNT: 'CON/v1/native-clearing-account',
  NATIVE_CLEARING_MATCH_AUTHORIZATION: 'CON/v1/native-clearing-match-authorization',
  NATIVE_CLEARING_MATCH: 'CON/v1/native-clearing-match',
  NATIVE_CLEARING_DEFAULT: 'CON/v1/native-clearing-default',
  RISK_DOMAIN_MANIFEST: 'CON/v1/risk-domain-manifest',
  COLLATERAL_SNAPSHOT: 'CON/v1/collateral-snapshot',
  PORTFOLIO_OPTIMIZATION_POLICY: 'CON/v1/portfolio-optimization-policy',
  PORTFOLIO_OPTIMIZATION_CANDIDATE: 'CON/v1/portfolio-optimization-candidate',
  PORTFOLIO_OPTIMIZATION_DECISION: 'CON/v1/portfolio-optimization-decision',
  STRATEGY_STATE: 'CON/v1/strategy-state',
  STRATEGY_TRANSITION: 'CON/v1/strategy-transition',
  PRIVATE_RFQ_RESPONSE: 'CON/v1/private-rfq-response',
  SEALED_AUCTION: 'CON/v1/sealed-auction',
  SEALED_COMMITMENT: 'CON/v1/sealed-commitment',
  SEALED_AUCTION_RESULT: 'CON/v1/sealed-auction-result',
  DISCLOSURE_FIELD: 'CON/v1/disclosure-field',
  DISCLOSURE_ROOT: 'CON/v1/disclosure-root',
  PRIVACY_PROFILE: 'CON/v1/privacy-profile',
  ROUTE_CANDIDATE_SET: 'CON/v1/route-candidate-set',
  ROUTE_SELECTION_OBJECTIVE: 'CON/v1/route-selection-objective',
  ROUTE_DECISION: 'CON/v1/route-decision',
  EXECUTION_QUALITY: 'CON/v1/execution-quality',
  DELIVERY_EVIDENCE: 'CON/v1/delivery-evidence',
  EXECUTION_INTELLIGENCE: 'CON/v1/execution-intelligence',
  INDEXED_PACKAGE_RECORD: 'CON/v1/indexed-package-record',
  PACKAGE_QUOTE_SHARD: 'CON/v1/package-quote-shard',
  RECONCILIATION_REPORT: 'CON/v1/reconciliation-report',
  SOLVER_REQUEST: 'CON/v1/solver-request',
  QUOTE_REFERENCE_STATE: 'CON/v1/quote-reference-state',
  ACTIVATION_CONDITION: 'CON/v1/activation-condition',
  EXECUTION_SCHEDULE: 'CON/v1/execution-schedule',
  STRATEGY_HEALTH: 'CON/v1/strategy-health',
  KEEPER_ACTION: 'CON/v1/keeper-action',
  QUALIFICATION_RECORD: 'CON/v1/qualification-record',
  FEE_PROMOTION_COHORT: 'CON/v1/fee-promotion-cohort',
  POSITION_SNAPSHOT: 'CON/v1/position-snapshot',
  PACKAGE_GRAPH: 'CON/v1/package-graph',
  STRATEGY_ORDER: 'CON/v1/strategy-order',
  STRATEGY_QUOTE: 'CON/v1/strategy-quote',
  STRATEGY_ROUTE: 'CON/v1/strategy-route',
  STRATEGY_RECEIPT: 'CON/v1/strategy-receipt',
  STRATEGY_RISK_SNAPSHOT: 'CON/v1/strategy-risk-snapshot',
  MARKET_CATALOGUE: 'CON/v1/market-catalogue',
  SHARD_FILL: 'CON/v1/shard-fill',
  STRATEGY_COMMAND: 'CON/v1/strategy-command',
  CROSS_DOMAIN_PLAN: 'CON/v1/cross-domain-plan',
  CROSS_DOMAIN_COMPENSATION: 'CON/v1/cross-domain-compensation',
  MANUAL_RECOVERY_INCIDENT: 'CON/v1/manual-recovery-incident',
  MAINNET_FUNDS_MANIFEST: 'CON/v1/mainnet-funds-manifest',
  BUILDER_MANIFEST: 'CON/v1/builder-manifest',
  BUILDER_ATTRIBUTION: 'CON/v1/builder-attribution',
  MANUAL_RECOVERY_APPROVAL: 'CON/v1/manual-recovery-approval',
} as const);

export type HashDomain = (typeof HASH_DOMAIN)[keyof typeof HASH_DOMAIN];

const DOMAIN_VALUES: readonly string[] = Object.freeze(Object.values(HASH_DOMAIN));

export function domainBytes(domain: HashDomain, context = 'hashDomain'): Uint8Array {
  if (!DOMAIN_VALUES.includes(domain)) {
    throw new MalformedInputError(context, `unregistered hash domain ${String(domain)}`);
  }
  return encodeAscii(domain, context);
}

export function domainHash(
  domain: HashDomain,
  payload: Uint8Array,
  context = 'domainHash',
): Hash32 {
  assertUint8Array(payload, `${context}.payload`);
  return hash32(sha256(concatBytes([domainBytes(domain, context), payload])), context);
}
