export {
  ProtocolError,
  RangeViolationError,
  MalformedInputError,
  DuplicateElementError,
  IncompatibleUnitError,
  DivisionByZeroError,
  type ProtocolErrorCode,
} from './errors.js';

export {
  toHex,
  fromHex,
  concatBytes,
  compareBytes,
  bytesEqual,
  assertUint8Array,
} from './bytes.js';

export { encodeUtf8, encodeAscii } from './text.js';

export {
  EXPIRY_UNIT,
  DURATION_UNIT,
  DIRECTION,
  PACKAGE_ACTION,
  PACKAGE_ORDER_TYPE,
  PACKAGE_TIME_IN_FORCE,
  RECOVERY_ACTION,
  SETTLEMENT_CLASS,
  QUANTITY_POLICY_CLASS,
  PARTIAL_FILL_POLICY,
  EXECUTION_PLAN_KIND,
  LEG_ROLE,
  TRADE_SIDE,
  LATE_BOUND_FIELD_KIND,
  COMPARATOR,
  STATE_VALUE_KIND,
  REGISTRY_STATE,
  REGISTRY_RECORD_KIND,
  RISK_LIMIT_KIND,
  FEE_CATEGORY,
  PASS_THROUGH_COST_CATEGORY,
  SERVICE_FEE_RATE_BASE,
  ROUNDING_DIRECTION,
  REFUND_RULE,
  ADAPTER_IDENTITY_SOURCE,
  ADAPTER_ACCESS_MODE,
  ADAPTER_SIGNER_MODE,
  SOLVER_SIGNATURE_SCHEME,
  QUOTE_MODE,
  QUOTED_OUTCOME_KIND,
  enumDiscriminant,
  type EnumTable,
  type ExpiryUnit,
  type DurationUnit,
  type Direction,
  type PackageAction,
  type PackageOrderType,
  type PackageTimeInForce,
  type RecoveryAction,
  type SettlementClass,
  type QuantityPolicyClass,
  type PartialFillPolicy,
  type ExecutionPlanKind,
  type LegRole,
  type TradeSide,
  type LateBoundFieldKind,
  type Comparator,
  type StateValueKind,
  type RegistryState,
  type RegistryRecordKind,
  type RiskLimitKind,
  type FeeCategory,
  type PassThroughCostCategory,
  type ServiceFeeRateBase,
  type RoundingDirection,
  type RefundRule,
  type AdapterIdentitySource,
  type AdapterAccessMode,
  type AdapterSignerMode,
  type SolverSignatureScheme,
  type QuoteMode,
  type QuotedOutcomeKind,
} from './enums.js';

export {
  serviceFeeRule,
  encodeServiceFeeRule,
  serviceFeeRuleKeyBytes,
  canonicalServiceFeeRules,
  passThroughCostRule,
  encodePassThroughCostRule,
  passThroughCostRuleKeyBytes,
  canonicalPassThroughCostRules,
  type ServiceFeeRuleInput,
  type ServiceFeeRule,
  type PassThroughCostRuleInput,
  type PassThroughCostRule,
} from './fee-policy-primitives.js';

export {
  feePolicyManifest,
  encodeFeePolicyManifest,
  feePolicyManifestBytes,
  feePolicyManifestHash,
  type FeePolicyManifestInput,
  type FeePolicyManifest,
} from './fee-policy-manifest.js';

export {
  ROUNDING,
  U32_MAX,
  toBigInt,
  checkedUnsigned,
  checkedSigned,
  absBigInt,
  assertU32Length,
  mulDiv,
  scaleDecimals,
  type Rounding,
} from './arithmetic.js';

export {
  CanonicalWriter,
  canonicalBytes,
  OPTIONAL_ABSENT,
  OPTIONAL_PRESENT,
  UNSIGNED_WIDTHS,
  SIGNED_WIDTHS,
  type ElementEncoder,
  type UnsignedWidth,
  type SignedWidth,
} from './encoding.js';

export {
  HASH_BYTE_LENGTH,
  PROTOCOL_ID_MAX_BYTES,
  MANIFEST_VERSION_BITS,
  ASSET_ATOM_BITS,
  EXPIRY_VALUE_BITS,
  DURATION_VALUE_BITS,
  hash32,
  encodeHash32,
  manifestHash,
  encodeManifestHash,
  protocolId,
  encodeProtocolId,
  domainId,
  assetId,
  versionedManifestRef,
  encodeVersionedManifestRef,
  domainRef,
  encodeDomainRef,
  assetRef,
  encodeAssetRef,
  assetAmount,
  encodeAssetAmount,
  expiry,
  encodeExpiry,
  compareExpiry,
  duration,
  encodeDuration,
  type Hash32,
  type ManifestHash,
  type ProtocolId,
  type DomainId,
  type AssetId,
  type VersionedManifestRef,
  type DomainRef,
  type AssetRef,
  type AssetAmount,
  type Expiry,
  type Duration,
} from './primitives.js';

export {
  commitmentHash,
  encodeCommitmentHash,
  exactPrice,
  encodeExactPrice,
  exactSignedRate,
  encodeExactSignedRate,
  adapterRef,
  encodeAdapterRef,
  feeCap,
  encodeFeeCap,
  canonicalFeeCaps,
  canonicalAdapterRefs,
  type CommitmentHash,
  type ExactPriceInput,
  type ExactPrice,
  type ExactSignedRateInput,
  type ExactSignedRate,
  type AdapterRefInput,
  type AdapterRef,
  type FeeCapInput,
  type FeeCap,
} from './package-order-primitives.js';

export {
  packageOrder,
  encodePackageOrder,
  packageOrderBytes,
  packageOrderHash,
  type PackageOrderInput,
  type PackageOrder,
} from './package-order.js';

export { validatePackageOrderProfile } from './package-order-profile.js';

export { HASH_DOMAIN, domainBytes, domainHash, type HashDomain } from './hashing.js';

export {
  quotedOutcome,
  encodeQuotedOutcome,
  solverQuote,
  encodeUnsignedSolverQuote,
  encodeSolverQuote,
  unsignedSolverQuoteBytes,
  solverQuoteBytes,
  quoteHash,
  solverSignatureDigest,
  type QuotedOutcomeInput,
  type QuotedOutcome,
  type SolverQuoteInput,
  type SolverQuote,
} from './solver-quote.js';

export {
  routeAccountBinding,
  encodeRouteAccountBinding,
  routeServiceCharge,
  encodeRouteServiceCharge,
  legExecution,
  encodeLegExecution,
  actionAccountMeta,
  encodeActionAccountMeta,
  lateBoundField,
  encodeLateBoundField,
  payloadTemplateHash,
  payloadTemplateCommitment,
  encodePayloadTemplateCommitment,
  actionCommitment,
  encodeActionCommitment,
  stateValue,
  encodeStateValue,
  stateConstraint,
  encodeStateConstraint,
  evidenceRequirements,
  encodeEvidenceRequirements,
  recoveryActionSlot,
  encodeRecoveryActionSlot,
  recoveryPlan,
  encodeRecoveryPlan,
  routePayload,
  encodeRoutePayload,
  routePayloadBytes,
  routeHash,
  routeAccountsHash,
  type PositiveAssetAmountInput,
  type PositiveAssetAmount,
  type UnsignedAssetAmountInput,
  type UnsignedAssetAmount,
  type NativeAssetValueInput,
  type NativeAssetValue,
  type RouteAccountBindingInput,
  type RouteAccountBinding,
  type RouteServiceChargeInput,
  type RouteServiceCharge,
  type LegExecutionInput,
  type LegExecution,
  type ActionAccountMetaInput,
  type ActionAccountMeta,
  type LateBoundFieldInput,
  type LateBoundField,
  type PayloadTemplateCommitmentInput,
  type PayloadTemplateCommitment,
  type ActionCommitmentInput,
  type ActionCommitment,
  type StateValueInput,
  type StateValue,
  type StateConstraintInput,
  type StateConstraint,
  type EvidenceRequirementsInput,
  type EvidenceRequirements,
  type RecoveryActionSlotInput,
  type RecoveryActionSlot,
  type RecoveryPlanInput,
  type RecoveryPlan,
  type RoutePayloadInput,
  type RoutePayload,
} from './route-payload.js';

export {
  domainManifest,
  encodeDomainManifest,
  domainManifestBytes,
  domainManifestHash,
  domainRefFromManifest,
  type DomainManifestInput,
  type DomainManifest,
} from './domain-manifest.js';

export {
  assetManifest,
  encodeAssetManifest,
  assetManifestBytes,
  assetManifestHash,
  assetRefFromManifest,
  type AssetManifestInput,
  type AssetManifest,
} from './asset-manifest.js';

export {
  venueManifest,
  encodeVenueManifest,
  venueManifestBytes,
  venueManifestHash,
  type VenueManifestInput,
  type VenueManifest,
} from './venue-manifest.js';

export {
  marketManifest,
  encodeMarketManifest,
  marketManifestBytes,
  marketManifestHash,
  type BaseLotSizeInput,
  type BaseLotSize,
  type PriceTickInput,
  type PriceTick,
  type MinimumNotionalInput,
  type MinimumNotional,
  type ContractMultiplierInput,
  type ContractMultiplier,
  type PermittedPriceSourceInput,
  type PermittedPriceSource,
  type MarketManifestInput,
  type MarketManifest,
} from './market-manifest.js';

export {
  packageTemplateManifest,
  encodePackageTemplateManifest,
  packageTemplateManifestBytes,
  packageTemplateManifestHash,
  type PackageTemplateManifestInput,
  type PackageTemplateManifest,
} from './package-template-manifest.js';

export {
  priceSourceManifest,
  encodePriceSourceManifest,
  priceSourceManifestBytes,
  priceSourceManifestHash,
  type PriceSourceManifestInput,
  type PriceSourceManifest,
} from './price-source-manifest.js';

export {
  packageTemplateRegistryRecord,
  encodePackageTemplateRegistryRecord,
  packageTemplateRegistryRecordBytes,
  packageTemplateRegistryRecordHash,
  type PackageTemplateRegistryRecordInput,
  type PackageTemplateRegistryRecord,
} from './package-template-registry-record.js';

export {
  RISK_LIMIT_COMPARISON_BITS,
  REGISTRY_CHANGE_CLASS,
  packageTemplateRef,
  encodePackageTemplateRef,
  packageTemplateRefKeyBytes,
  riskLimit,
  encodeRiskLimit,
  riskLimitKeyBytes,
  canonicalRiskLimits,
  canonicalPackageTemplateRefs,
  classifyRiskLimitChange,
  type RegistryChangeClass,
  type PackageTemplateRefInput,
  type PackageTemplateRef,
  type RiskLimitInput,
  type RiskLimit,
} from './registry-primitives.js';

export {
  encodeAdapterMarketRef,
  encodeAdapterAssetRef,
  identityConstraint,
  encodeIdentityConstraint,
  signerRule,
  encodeSignerRule,
  accountAndAuthorityBinding,
  encodeAccountAndAuthorityBinding,
  adapterManifest,
  encodeAdapterManifest,
  adapterManifestBytes,
  adapterManifestHash,
  type AdapterMarketRefInput,
  type AdapterMarketRef,
  type AdapterAssetRefInput,
  type AdapterAssetRef,
  type IdentityConstraintInput,
  type IdentityConstraint,
  type SignerRuleInput,
  type SignerRule,
  type AccountAndAuthorityBindingInput,
  type AccountAndAuthorityBinding,
  type AdapterManifestInput,
  type AdapterManifest,
} from './adapter-manifest.js';

export {
  domainRegistryRecord,
  encodeDomainRegistryRecord,
  domainRegistryRecordBytes,
  domainRegistryRecordHash,
  type DomainRegistryRecordInput,
  type DomainRegistryRecord,
} from './domain-registry-record.js';
